//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;
using Unity.IL2CPP.CompilerServices;

#pragma warning disable 0660, 0661

namespace Fraktalia.Core.Mathematics
{
    /// <summary>A 2 component vector of floats.</summary>
    [DebuggerTypeProxy(typeof(Ffloat2.DebuggerProxy))]
    [System.Serializable]
    [FIl2CppEagerStaticClassConstruction]
    public partial struct Ffloat2 : System.IEquatable<Ffloat2>, IFormattable
    {
        /// <summary>x component of the vector.</summary>
        public float x;
        /// <summary>y component of the vector.</summary>
        public float y;

        /// <summary>float2 zero value.</summary>
        public static readonly Ffloat2 zero;

        /// <summary>Constructs a float2 vector from two float values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(float x, float y)
        {
            this.x = x;
            this.y = y;
        }

        /// <summary>Constructs a float2 vector from a float2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(Ffloat2 xy)
        {
            this.x = xy.x;
            this.y = xy.y;
        }

        /// <summary>Constructs a float2 vector from a single float value by assigning it to every component.</summary>
        /// <param name="v">float to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(float v)
        {
            this.x = v;
            this.y = v;
        }

        /// <summary>Constructs a float2 vector from a single bool value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">bool to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(bool v)
        {
            this.x = v ? 1.0f : 0.0f;
            this.y = v ? 1.0f : 0.0f;
        }

        /// <summary>Constructs a float2 vector from a bool2 vector by componentwise conversion.</summary>
        /// <param name="v">bool2 to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(Fbool2 v)
        {
            this.x = v.x ? 1.0f : 0.0f;
            this.y = v.y ? 1.0f : 0.0f;
        }

        /// <summary>Constructs a float2 vector from a single int value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">int to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(int v)
        {
            this.x = v;
            this.y = v;
        }

        /// <summary>Constructs a float2 vector from a int2 vector by componentwise conversion.</summary>
        /// <param name="v">int2 to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(Fint2 v)
        {
            this.x = v.x;
            this.y = v.y;
        }

        /// <summary>Constructs a float2 vector from a single uint value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">uint to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(uint v)
        {
            this.x = v;
            this.y = v;
        }

        /// <summary>Constructs a float2 vector from a uint2 vector by componentwise conversion.</summary>
        /// <param name="v">uint2 to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(Fuint2 v)
        {
            this.x = v.x;
            this.y = v.y;
        }

        /// <summary>Constructs a float2 vector from a single half value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">half to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(Fhalf v)
        {
            this.x = v;
            this.y = v;
        }

        /// <summary>Constructs a float2 vector from a half2 vector by componentwise conversion.</summary>
        /// <param name="v">half2 to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(Fhalf2 v)
        {
            this.x = v.x;
            this.y = v.y;
        }

        /// <summary>Constructs a float2 vector from a single double value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">double to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(double v)
        {
            this.x = (float)v;
            this.y = (float)v;
        }

        /// <summary>Constructs a float2 vector from a double2 vector by componentwise conversion.</summary>
        /// <param name="v">double2 to convert to float2</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Ffloat2(Fdouble2 v)
        {
            this.x = (float)v.x;
            this.y = (float)v.y;
        }


        /// <summary>Implicitly converts a single float value to a float2 vector by assigning it to every component.</summary>
        /// <param name="v">float to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Ffloat2(float v) { return new Ffloat2(v); }

        /// <summary>Explicitly converts a single bool value to a float2 vector by converting it to float and assigning it to every component.</summary>
        /// <param name="v">bool to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Ffloat2(bool v) { return new Ffloat2(v); }

        /// <summary>Explicitly converts a bool2 vector to a float2 vector by componentwise conversion.</summary>
        /// <param name="v">bool2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Ffloat2(Fbool2 v) { return new Ffloat2(v); }

        /// <summary>Implicitly converts a single int value to a float2 vector by converting it to float and assigning it to every component.</summary>
        /// <param name="v">int to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Ffloat2(int v) { return new Ffloat2(v); }

        /// <summary>Implicitly converts a int2 vector to a float2 vector by componentwise conversion.</summary>
        /// <param name="v">int2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Ffloat2(Fint2 v) { return new Ffloat2(v); }

        /// <summary>Implicitly converts a single uint value to a float2 vector by converting it to float and assigning it to every component.</summary>
        /// <param name="v">uint to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Ffloat2(uint v) { return new Ffloat2(v); }

        /// <summary>Implicitly converts a uint2 vector to a float2 vector by componentwise conversion.</summary>
        /// <param name="v">uint2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Ffloat2(Fuint2 v) { return new Ffloat2(v); }

        /// <summary>Implicitly converts a single half value to a float2 vector by converting it to float and assigning it to every component.</summary>
        /// <param name="v">half to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Ffloat2(Fhalf v) { return new Ffloat2(v); }

        /// <summary>Implicitly converts a half2 vector to a float2 vector by componentwise conversion.</summary>
        /// <param name="v">half2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Ffloat2(Fhalf2 v) { return new Ffloat2(v); }

        /// <summary>Explicitly converts a single double value to a float2 vector by converting it to float and assigning it to every component.</summary>
        /// <param name="v">double to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Ffloat2(double v) { return new Ffloat2(v); }

        /// <summary>Explicitly converts a double2 vector to a float2 vector by componentwise conversion.</summary>
        /// <param name="v">double2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Ffloat2(Fdouble2 v) { return new Ffloat2(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise multiplication.</param>
        /// <returns>float2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator * (Ffloat2 lhs, Ffloat2 rhs) { return new Ffloat2 (lhs.x * rhs.x, lhs.y * rhs.y); }

        /// <summary>Returns the result of a componentwise multiplication operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise multiplication.</param>
        /// <returns>float2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator * (Ffloat2 lhs, float rhs) { return new Ffloat2 (lhs.x * rhs, lhs.y * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise multiplication.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise multiplication.</param>
        /// <returns>float2 result of the componentwise multiplication.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator * (float lhs, Ffloat2 rhs) { return new Ffloat2 (lhs * rhs.x, lhs * rhs.y); }


        /// <summary>Returns the result of a componentwise addition operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise addition.</param>
        /// <returns>float2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator + (Ffloat2 lhs, Ffloat2 rhs) { return new Ffloat2 (lhs.x + rhs.x, lhs.y + rhs.y); }

        /// <summary>Returns the result of a componentwise addition operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise addition.</param>
        /// <returns>float2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator + (Ffloat2 lhs, float rhs) { return new Ffloat2 (lhs.x + rhs, lhs.y + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise addition.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise addition.</param>
        /// <returns>float2 result of the componentwise addition.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator + (float lhs, Ffloat2 rhs) { return new Ffloat2 (lhs + rhs.x, lhs + rhs.y); }


        /// <summary>Returns the result of a componentwise subtraction operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise subtraction.</param>
        /// <returns>float2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator - (Ffloat2 lhs, Ffloat2 rhs) { return new Ffloat2 (lhs.x - rhs.x, lhs.y - rhs.y); }

        /// <summary>Returns the result of a componentwise subtraction operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise subtraction.</param>
        /// <returns>float2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator - (Ffloat2 lhs, float rhs) { return new Ffloat2 (lhs.x - rhs, lhs.y - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise subtraction.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise subtraction.</param>
        /// <returns>float2 result of the componentwise subtraction.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator - (float lhs, Ffloat2 rhs) { return new Ffloat2 (lhs - rhs.x, lhs - rhs.y); }


        /// <summary>Returns the result of a componentwise division operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise division.</param>
        /// <returns>float2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator / (Ffloat2 lhs, Ffloat2 rhs) { return new Ffloat2 (lhs.x / rhs.x, lhs.y / rhs.y); }

        /// <summary>Returns the result of a componentwise division operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise division.</param>
        /// <returns>float2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator / (Ffloat2 lhs, float rhs) { return new Ffloat2 (lhs.x / rhs, lhs.y / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise division.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise division.</param>
        /// <returns>float2 result of the componentwise division.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator / (float lhs, Ffloat2 rhs) { return new Ffloat2 (lhs / rhs.x, lhs / rhs.y); }


        /// <summary>Returns the result of a componentwise modulus operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise modulus.</param>
        /// <returns>float2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator % (Ffloat2 lhs, Ffloat2 rhs) { return new Ffloat2 (lhs.x % rhs.x, lhs.y % rhs.y); }

        /// <summary>Returns the result of a componentwise modulus operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise modulus.</param>
        /// <returns>float2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator % (Ffloat2 lhs, float rhs) { return new Ffloat2 (lhs.x % rhs, lhs.y % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise modulus.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise modulus.</param>
        /// <returns>float2 result of the componentwise modulus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator % (float lhs, Ffloat2 rhs) { return new Ffloat2 (lhs % rhs.x, lhs % rhs.y); }


        /// <summary>Returns the result of a componentwise increment operation on a float2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise increment.</param>
        /// <returns>float2 result of the componentwise increment.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator ++ (Ffloat2 val) { return new Ffloat2 (++val.x, ++val.y); }


        /// <summary>Returns the result of a componentwise decrement operation on a float2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise decrement.</param>
        /// <returns>float2 result of the componentwise decrement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator -- (Ffloat2 val) { return new Ffloat2 (--val.x, --val.y); }


        /// <summary>Returns the result of a componentwise less than operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator < (Ffloat2 lhs, Ffloat2 rhs) { return new Fbool2 (lhs.x < rhs.x, lhs.y < rhs.y); }

        /// <summary>Returns the result of a componentwise less than operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator < (Ffloat2 lhs, float rhs) { return new Fbool2 (lhs.x < rhs, lhs.y < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise less than.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise less than.</param>
        /// <returns>bool2 result of the componentwise less than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator < (float lhs, Ffloat2 rhs) { return new Fbool2 (lhs < rhs.x, lhs < rhs.y); }


        /// <summary>Returns the result of a componentwise less or equal operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator <= (Ffloat2 lhs, Ffloat2 rhs) { return new Fbool2 (lhs.x <= rhs.x, lhs.y <= rhs.y); }

        /// <summary>Returns the result of a componentwise less or equal operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator <= (Ffloat2 lhs, float rhs) { return new Fbool2 (lhs.x <= rhs, lhs.y <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise less or equal.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise less or equal.</param>
        /// <returns>bool2 result of the componentwise less or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator <= (float lhs, Ffloat2 rhs) { return new Fbool2 (lhs <= rhs.x, lhs <= rhs.y); }


        /// <summary>Returns the result of a componentwise greater than operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator > (Ffloat2 lhs, Ffloat2 rhs) { return new Fbool2 (lhs.x > rhs.x, lhs.y > rhs.y); }

        /// <summary>Returns the result of a componentwise greater than operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator > (Ffloat2 lhs, float rhs) { return new Fbool2 (lhs.x > rhs, lhs.y > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise greater than.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise greater than.</param>
        /// <returns>bool2 result of the componentwise greater than.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator > (float lhs, Ffloat2 rhs) { return new Fbool2 (lhs > rhs.x, lhs > rhs.y); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator >= (Ffloat2 lhs, Ffloat2 rhs) { return new Fbool2 (lhs.x >= rhs.x, lhs.y >= rhs.y); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator >= (Ffloat2 lhs, float rhs) { return new Fbool2 (lhs.x >= rhs, lhs.y >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise greater or equal.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise greater or equal.</param>
        /// <returns>bool2 result of the componentwise greater or equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator >= (float lhs, Ffloat2 rhs) { return new Fbool2 (lhs >= rhs.x, lhs >= rhs.y); }


        /// <summary>Returns the result of a componentwise unary minus operation on a float2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary minus.</param>
        /// <returns>float2 result of the componentwise unary minus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator - (Ffloat2 val) { return new Ffloat2 (-val.x, -val.y); }


        /// <summary>Returns the result of a componentwise unary plus operation on a float2 vector.</summary>
        /// <param name="val">Value to use when computing the componentwise unary plus.</param>
        /// <returns>float2 result of the componentwise unary plus.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 operator + (Ffloat2 val) { return new Ffloat2 (+val.x, +val.y); }


        /// <summary>Returns the result of a componentwise equality operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator == (Ffloat2 lhs, Ffloat2 rhs) { return new Fbool2 (lhs.x == rhs.x, lhs.y == rhs.y); }

        /// <summary>Returns the result of a componentwise equality operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator == (Ffloat2 lhs, float rhs) { return new Fbool2 (lhs.x == rhs, lhs.y == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise equality.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise equality.</param>
        /// <returns>bool2 result of the componentwise equality.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator == (float lhs, Ffloat2 rhs) { return new Fbool2 (lhs == rhs.x, lhs == rhs.y); }


        /// <summary>Returns the result of a componentwise not equal operation on two float2 vectors.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator != (Ffloat2 lhs, Ffloat2 rhs) { return new Fbool2 (lhs.x != rhs.x, lhs.y != rhs.y); }

        /// <summary>Returns the result of a componentwise not equal operation on a float2 vector and a float value.</summary>
        /// <param name="lhs">Left hand side float2 to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side float to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator != (Ffloat2 lhs, float rhs) { return new Fbool2 (lhs.x != rhs, lhs.y != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a float value and a float2 vector.</summary>
        /// <param name="lhs">Left hand side float to use to compute componentwise not equal.</param>
        /// <param name="rhs">Right hand side float2 to use to compute componentwise not equal.</param>
        /// <returns>bool2 result of the componentwise not equal.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fbool2 operator != (float lhs, Ffloat2 rhs) { return new Fbool2 (lhs != rhs.x, lhs != rhs.y); }




        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 xyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(x, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat4 yyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat4(y, y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 xxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(x, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 xxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(x, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 xyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(x, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 xyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(x, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 yxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(y, x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 yxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(y, x, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 yyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(y, y, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat3 yyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat3(y, y, y); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat2 xx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat2(x, x); }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat2 xy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat2(x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat2 yx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat2(y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; }
        }


        /// <summary>Swizzles the vector.</summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Ffloat2 yy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new Ffloat2(y, y); }
        }



        /// <summary>Returns the float element at a specified index.</summary>
        unsafe public float this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (Ffloat2* array = &this) { return ((float*)array)[index]; }
            }
            set
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 2)
                    throw new System.ArgumentException("index must be between[0...1]");
#endif
                fixed (float* array = &x) { array[index] = value; }
            }
        }

        /// <summary>Returns true if the float2 is equal to a given float2, false otherwise.</summary>
        /// <param name="rhs">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(Ffloat2 rhs) { return x == rhs.x && y == rhs.y; }

        /// <summary>Returns true if the float2 is equal to a given float2, false otherwise.</summary>
        /// <param name="o">Right hand side argument to compare equality with.</param>
        /// <returns>The result of the equality comparison.</returns>
        public override bool Equals(object o) { return o is Ffloat2 converted && Equals(converted); }


        /// <summary>Returns a hash code for the float2.</summary>
        /// <returns>The computed hash code.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)Fmath.hash(this); }


        /// <summary>Returns a string representation of the float2.</summary>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("float2({0}f, {1}f)", x, y);
        }

        /// <summary>Returns a string representation of the float2 using a specified format and culture-specific format information.</summary>
        /// <param name="format">Format string to use during string formatting.</param>
        /// <param name="formatProvider">Format provider to use during string formatting.</param>
        /// <returns>String representation of the value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("float2({0}f, {1}f)", x.ToString(format, formatProvider), y.ToString(format, formatProvider));
        }

        internal sealed class DebuggerProxy
        {
            public float x;
            public float y;
            public DebuggerProxy(Ffloat2 v)
            {
                x = v.x;
                y = v.y;
            }
        }

    }

    public static partial class Fmath
    {
        /// <summary>Returns a float2 vector constructed from two float values.</summary>
        /// <param name="x">The constructed vector's x component will be set to this value.</param>
        /// <param name="y">The constructed vector's y component will be set to this value.</param>
        /// <returns>float2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(float x, float y) { return new Ffloat2(x, y); }

        /// <summary>Returns a float2 vector constructed from a float2 vector.</summary>
        /// <param name="xy">The constructed vector's xy components will be set to this value.</param>
        /// <returns>float2 constructed from arguments.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(Ffloat2 xy) { return new Ffloat2(xy); }

        /// <summary>Returns a float2 vector constructed from a single float value by assigning it to every component.</summary>
        /// <param name="v">float to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(float v) { return new Ffloat2(v); }

        /// <summary>Returns a float2 vector constructed from a single bool value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">bool to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(bool v) { return new Ffloat2(v); }

        /// <summary>Return a float2 vector constructed from a bool2 vector by componentwise conversion.</summary>
        /// <param name="v">bool2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(Fbool2 v) { return new Ffloat2(v); }

        /// <summary>Returns a float2 vector constructed from a single int value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">int to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(int v) { return new Ffloat2(v); }

        /// <summary>Return a float2 vector constructed from a int2 vector by componentwise conversion.</summary>
        /// <param name="v">int2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(Fint2 v) { return new Ffloat2(v); }

        /// <summary>Returns a float2 vector constructed from a single uint value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">uint to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(uint v) { return new Ffloat2(v); }

        /// <summary>Return a float2 vector constructed from a uint2 vector by componentwise conversion.</summary>
        /// <param name="v">uint2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(Fuint2 v) { return new Ffloat2(v); }

        /// <summary>Returns a float2 vector constructed from a single half value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">half to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(Fhalf v) { return new Ffloat2(v); }

        /// <summary>Return a float2 vector constructed from a half2 vector by componentwise conversion.</summary>
        /// <param name="v">half2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(Fhalf2 v) { return new Ffloat2(v); }

        /// <summary>Returns a float2 vector constructed from a single double value by converting it to float and assigning it to every component.</summary>
        /// <param name="v">double to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(double v) { return new Ffloat2(v); }

        /// <summary>Return a float2 vector constructed from a double2 vector by componentwise conversion.</summary>
        /// <param name="v">double2 to convert to float2</param>
        /// <returns>Converted value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 float2(Fdouble2 v) { return new Ffloat2(v); }

        /// <summary>Returns a uint hash code of a float2 vector.</summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>uint hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(Ffloat2 v)
        {
            return csum(asuint(v) * uint2(0xFA3A3285u, 0xAD55999Du)) + 0xDCDD5341u;
        }

        /// <summary>
        /// Returns a uint2 vector hash code of a float2 vector.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        /// <param name="v">Vector value to hash.</param>
        /// <returns>uint2 hash of the argument.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Fuint2 hashwide(Ffloat2 v)
        {
            return (asuint(v) * uint2(0x94DDD769u, 0xA1E92D39u)) + 0x4583C801u;
        }

        /// <summary>Returns the result of specified shuffling of the components from two float2 vectors into a float value.</summary>
        /// <param name="left">float2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">float2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting float.</param>
        /// <returns>float result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float shuffle(Ffloat2 left, Ffloat2 right, ShuffleComponent x)
        {
            return select_shuffle_component(left, right, x);
        }

        /// <summary>Returns the result of specified shuffling of the components from two float2 vectors into a float2 vector.</summary>
        /// <param name="left">float2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">float2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting float2 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting float2 y component.</param>
        /// <returns>float2 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat2 shuffle(Ffloat2 left, Ffloat2 right, ShuffleComponent x, ShuffleComponent y)
        {
            return float2(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y));
        }

        /// <summary>Returns the result of specified shuffling of the components from two float2 vectors into a float3 vector.</summary>
        /// <param name="left">float2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">float2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting float3 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting float3 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting float3 z component.</param>
        /// <returns>float3 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat3 shuffle(Ffloat2 left, Ffloat2 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z)
        {
            return float3(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z));
        }

        /// <summary>Returns the result of specified shuffling of the components from two float2 vectors into a float4 vector.</summary>
        /// <param name="left">float2 to use as the left argument of the shuffle operation.</param>
        /// <param name="right">float2 to use as the right argument of the shuffle operation.</param>
        /// <param name="x">The ShuffleComponent to use when setting the resulting float4 x component.</param>
        /// <param name="y">The ShuffleComponent to use when setting the resulting float4 y component.</param>
        /// <param name="z">The ShuffleComponent to use when setting the resulting float4 z component.</param>
        /// <param name="w">The ShuffleComponent to use when setting the resulting float4 w component.</param>
        /// <returns>float4 result of the shuffle operation.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Ffloat4 shuffle(Ffloat2 left, Ffloat2 right, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z, ShuffleComponent w)
        {
            return float4(
                select_shuffle_component(left, right, x),
                select_shuffle_component(left, right, y),
                select_shuffle_component(left, right, z),
                select_shuffle_component(left, right, w));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static float select_shuffle_component(Ffloat2 a, Ffloat2 b, ShuffleComponent component)
        {
            switch(component)
            {
                case ShuffleComponent.LeftX:
                    return a.x;
                case ShuffleComponent.LeftY:
                    return a.y;
                case ShuffleComponent.RightX:
                    return b.x;
                case ShuffleComponent.RightY:
                    return b.y;
                default:
                    throw new System.ArgumentException("Invalid shuffle component: " + component);
            }
        }

    }
}
